server:
  port: 8088

spring:
  application:
    name: qwen
  profiles:
    active: dev
  ai:
    openai:
      base-url: https://api.openai.com/
      api-key: sk-xxx
      embedding:
        options:
          model: xxxx
      chat:
        api-key: sk-xxx
        base-url: https://dashscope.aliyuncs.com/compatible-mode
        options:
          model: qwen2.5-72b-instruct
          response_format:
            type: json_object
